### ISSUE TITLE
Source of truth

### ISSUE THREAD

**Issue by dandv** [kadena-io/kadena-docs#7]
What's the source of truth for https://docs.kadena.io? (not for https://kadena-io.github.io/kadena-docs)

This repo doesn't seem to be it. For example, the [exchange summary](https://github.com/kadena-io/kadena-docs/blob/master/docs/exchange-summary.md) mentions a May 2021 update, while the [live docs](https://docs.kadena.io/exchanges) mention August 2021.

**Comment by dandv** [comment]
Hello? @mightybyte? @abuvanth? It's been a month.

People are [losing funds](https://www.reddit.com/r/kadena/comments/rf05kl/lost_kadena_from_exchange/) because the [Exchanges](https://docs.kadena.io/exchanges) page doesn't urge them to use `k:` accounts. I wanted to submit a PR advising of this, but I don't know where to do so.

**Comment by mightybyte** [comment]
This site is no longer being updated because it has been replaced by docs.kadena.io.  It is currently not hosted on GitHub.  We're working on improving things to leverage community contributions.  Bear with us though as it will take some time.

**Comment by dandv** [comment]
Got it, thanks. I've submitted a [PR to clarify the state of the repo](https://github.com/kadena-io/kadena-docs/pull/8).

Maybe [archive the repo](https://docs.github.com/en/repositories/archiving-a-github-repository/archiving-repositories) after accepting the PR?
